[package]
name = "sinter_theme_default_light"
version = "0.1.0"
edition = "2024"

[dependencies]
sinter_core = { path = "../../../core" }
sinter_ui = { path = "../../../sinter_ui" }
sinter_theme_sdk = { path = "../../../theme_sdk" }
