[package]
name = "sinter_theme_default_light"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8", features = ["csr"] }
sinter_core = { path = "../../../core" }
sinter_theme_sdk = { path = "../../../theme_sdk" }
